webtalk_init -webtalk_dir C:/Users/Rudolf/Desktop/Apps/vivado_systemVerilog/304-Sesion4/304-Sesion4.sim/sim_1/behav/xsim/xsim.dir/Actividad1test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun  5 00:38:44 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fcb84f3b-dae0-43dc-a305-212821b48a30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "00512533563f477eabe1f5166e55e0bf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.78_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1461381702 -regid "" -xml C:/Users/Rudolf/Desktop/Apps/vivado_systemVerilog/304-Sesion4/304-Sesion4.sim/sim_1/behav/xsim/xsim.dir/Actividad1test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Rudolf/Desktop/Apps/vivado_systemVerilog/304-Sesion4/304-Sesion4.sim/sim_1/behav/xsim/xsim.dir/Actividad1test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Rudolf/Desktop/Apps/vivado_systemVerilog/304-Sesion4/304-Sesion4.sim/sim_1/behav/xsim/xsim.dir/Actividad1test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
